export const enum Token {
  AUTH_SERVICE = "AUTH_SERVICE",
  LOGIN_USE_CASE = "LOGIN_USE_CASE",
  NAVIGATOR = "NAVIGATOR",
  RECIPE_REPOSITORY = "RECIPE_REPOSITORY",
  TOKEN_REPOSITORY = "TOKEN_REPOSITORY",
  REACT_ROUTER_NAVIGATE = "REACT_ROUTER_NAVIGATE",
  I18NEXT = "I18NEXT",
  TRANSLATION_SERVICE = "TRANSLATION_SERVICE",
}
